function createfigure(YMatrix1, YMatrix2)
%CREATEFIGURE(YMatrix1, YMatrix2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 07-Jan-2018 13:59:57

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
set(plot1(2),'DisplayName','lead');
set(plot1(3),'DisplayName','lag');

% Create ylabel
ylabel('Price');

% Create xlabel
xlabel('Daily Sample');

% Create title
title('Closing Price');

box(subplot1,'on');
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2,'DisplayName','s');
set(plot2(2),'DisplayName','w');
set(plot2(3),'Visible','off');

% Create ylabel
ylabel('Return');

box(subplot2,'on');
grid(subplot2,'on');
