function createfigure1(YMatrix1, YMatrix2)
%CREATEFIGURE1(YMATRIX1, YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 11-Jan-2018 11:57:12

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
set(plot1(2),'DisplayName','lead');
set(plot1(3),'DisplayName','lag');

% Create xlabel
xlabel('Daily Sample');

% Create title
title('Closing Price');

% Create ylabel
ylabel('Price');

box(subplot1,'on');
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','s');
set(plot2(2),'DisplayName','cumsumr');

% Create ylabel
ylabel('Return');

box(subplot2,'on');
